myprofile/urls.py
from django.urls import path
from . import views

app_name = 'myprofile'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('Skills/', views.skills, name='skills'),
    path('Experience/', views.experience, name='experience'),
    path('Contact/', views.contact, name='contact'),
    path('Quotes/', views.quotes, name='quotes'),
]

myproject/urls.py
from django.urls import path, include
from django.contrib import admin


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myprofile.urls')),
]

myprofile/models.py
from django.db import models

# Create your models here.

myprofile/views.py
from django.shortcuts import render

def profile(request):
    return render(request, 'Profile.html')

def skills(request):
    return render(request, 'Skills.html')

def experience(request):
    return render(request, 'experience.html')

def contact(request):
    return render(request, 'Contact.html')
    

def quotes(request):
    return render(request, 'Quotes.html')
    
    
# Create your views here.

myprofile/templates/Contact.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Profile.css' %}">
    <link rel= "shortcut icon" href="logo.ico" type="image/x-icon">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-white sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img id="logo" src="{% static 'Images/Logo.png' %}"></a>

         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
          <span class="navbar-toggler-icon"></span>
         </button>
       
         <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
       
                <li class="nav-item active">
                        <a class="nav-link" href="{% url 'myprofile:profile' %}" id="fontnav">Home</a>
                       </li>
                   
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:experience' %}" id="fontnav">Skills</a>
                        </li>
                   
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:skills' %}" id="fontnav">Activities</a>
                       </li>
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:contact' %}" id="fontnav">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'myprofile:quotes' %}" id="fontnav">Quotes</a>
            </li>
          </ul>
         </div>
        </div>
       </nav>
       <!--halaman 6  -->
       <div class= "container-fluid-padding" id="tes">
            <div class="row text-center padding px-0 mx-0">
              <div class="col-xs-12 col-md-12" id="kotak7">
                  Contact.
              </div>
            </div>
        </div>

        <div class= "container-fluid-padding">
            <div class="row text-center padding px-0 mx-0">
              <div class="col-xs-12 col-md-6" id="kotak8">
                <img src="{% static 'Images/instagram.svg' %}"  id="logoig">
                <b>@bhaskorobsp</b>
              </div>
              <div class="col-xs-12 col-md-6" id="kotak9">
                  <img src="{% static 'Images/line.svg' %}"  id="logoline">
                  <b>bhaski</b> 
              </div>
            </div>
          </div>

        <!-- facebook -->
          <div class= "container-fluid-padding">
              <div class="row text-center padding px-0 mx-0">
                <div class="col-xs-12 col-md-12" id="kotak10">
                  <div>
                      <img src="{% static 'Images/facebook.svg' %}" id="logofacebook">
                      <b> Bhaskoro Siddhi Pradhana</b>
                  </div>
                </div>
              </div>
          </div>
        <!--Linkedin  -->
          <div class= "container-fluid-padding">
              <div class="row text-center padding px-0 mx-0">
                <div class="col-xs-12 col-md-12" id="kotak11">
                    <img src="{% static 'Images/linkedin.svg' %}"  id="logolinkedin">
                    <b>Bhaskoro Siddhi Pradhana</b> 
                </div>
              </div>
          </div>
        <!-- Email -->
          <div class= "container-fluid-padding">
              <div class="row text-center padding px-0 mx-0">
                <div class="col-xs-12 col-md-12" id="kotak12">
                    <img src="{% static 'Images/email.svg' %}"  id="logoemail" >
                      <b>bhaski.pradhana@gmail.com</b> 
                </div>
              </div>
          </div>
        
</body>

myprofile/templates/Profile.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Profile.css' %}">
    <link rel= "shortcut icon" href="logo.ico" type="image/x-icon">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-white sticky-top">
        <div class="container-fluid">
         <a class="navbar-brand" href="#"><img id="logo" src="{% static 'Logo.png' %}"></a>

         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
          <span class="navbar-toggler-icon"></span>
         </button>
       
         <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
       
           <li class="nav-item active">
            <a class="nav-link" href="{% url 'myprofile:profile' %}" id="fontnav">Home</a>
           </li>
       
           <li class="nav-item">
             <a class="nav-link" href="{% url 'myprofile:experience' %}" id="fontnav">Skills</a>
            </li>
       
           <li class="nav-item">
             <a class="nav-link" href="{% url 'myprofile:skills' %}" id="fontnav">Activities</a>
           </li>
           <li class="nav-item">
             <a class="nav-link" href="{% url 'myprofile:contact' %}" id="fontnav">Contact</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'myprofile:quotes' %}" id="fontnav">Quotes</a>
          </ul>
         </div>
        </div>
       </nav>

      <!-- halaman 1 -->
      <div class="container-fluid-padding" id="atas">
          <div class="row text-left padding px-0 mx-0">
        
            <div class="col-xs-12 col-sm-4" id="kotakkiri">
                <img src="{% static 'foto profile.jpg' %}" id="fotoprofile">
            </div>
        
            <div class="col-xs-12 col-sm-8" id="kotakkanan">

          
                  <h4 id="judul1">"Don’t be sorry,</h4>
                  <h4 id="judul2">be <span id="judulbeda">BETTER</span>"</h4>
                  <h6 id="informasi"> Extremely determined to learn new things outside the class. 
                    I am  really interested in business and marketing fields. 
                    I have a good interpersonal and communication skills, where I have tons of experience working and conducting other people.</h6>
              
              
            </div>
        
          </div>
        </div>

     <!-- halaman 2 -->
      <div class= "container-fluid-padding">
        <div class="row text-center padding px-0 mx-0">
          <div class="col-xs-12 col-md-6" id="kotak2">
              <p id="nama1">Bhaskoro Siddhi <br> Pradhana</p>
              
                <p id="nama2">Jakarta, 14 Februari 2000 <br>
                  +6287788137000 <br>
                  <br>
                  Komplek DPR no 6, Kemanggisan, Jakarta Barat.<br> </p>

          </div>
          <div class="col-xs-12 col-md-6" id="kotak2">
              <img src="{% static 'bhaski2.jpg' %}" id="foto2">
          </div>
        </div>
      </div>

      <div class= "container-fluid-padding">
          <div class="row text-center padding px-0 mx-0">
            <div class="col-xs-12 col-md-4" id="kotak3">
                <p id="sekolahsd"> <b>SD Bhakti YKKP</b><br>2006 - 2012</p>
            </div>
            <div class="col-xs-12 col-md-4" id="kotak3">
                <p id="sekolahsmp"> <b>SMP Labschool Kebayoran</b><br>
                  2012 - 2015</p>
            </div>
            <div class="col-xs-12 col-md-4" id="kotak3">
                <p id="sekolahsma"> <b>SMAN 78 Jakarta</b><br>2015 - 2018</p>
            </div>
          </div>
        </div>
      
        <div class= "container-fluid-padding">
            <div class="row text-center padding px-0 mx-0">
              <div class="col-xs-12 col col-md-12" id="kotak4">
                  <p id="sekolahkuliah"> <b>Sistem Informasi, Fakultas Ilmu Komputer, Universitas Indonesia</b><br>
                    2018 - Now</p>
              </div>
            </div>
          </div>
        
      
</body>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

myprofile/templates/Quotes.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Profile.css' %}">
    <link rel= "shortcut icon" href="logo.ico" type="image/x-icon">
    

</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-white sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img id="logo" src="{% static 'Images/Logo.png' %}"></a>

         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
          <span class="navbar-toggler-icon"></span>
         </button>
       
         <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
       
                <li class="nav-item active">
                        <a class="nav-link" href="{% url 'myprofile:profile' %}" id="fontnav">Home</a>
                       </li>
                   
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:experience' %}" id="fontnav">Skills</a>
                        </li>
                   
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:skills' %}" id="fontnav">Activities</a>
                       </li>
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:contact' %}" id="fontnav">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'myprofile:quotes' %}" id="fontnav">Quotes</a>
          </ul>
         </div>
        </div>
       </nav>
       <div class= "container-fluid-padding px-0 mx-0" id="kotakquotes">
            <div class="row text-center padding px-0 mx-0">
              <div class="col-xs-12 col-md-12 px-0 mx-0" >
                  <img src="{% static 'bhaski4.JPG' %}" id="bg10">
                  <p id="quotes">#DemokrasiDiKebiri</p> 
              </div>
            </div>
          </div>
        </body>

myprofile/templates/Skills.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Profile.css' %}">
    <link rel= "shortcut icon" href="logo.ico" type="image/x-icon">
</head>
<body>
  <nav class="navbar navbar-expand-md navbar-light bg-white sticky-top">
    <div class="container-fluid">
     <a class="navbar-brand" href="#"><img id="logo" src="{% static 'Logo.png' %}"></a>

     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
      <span class="navbar-toggler-icon"></span>
     </button>
   
     <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
   
       <li class="nav-item active">
        <a class="nav-link" href="{% url 'myprofile:profile' %}" id="fontnav">Home</a>
       </li>
   
       <li class="nav-item">
         <a class="nav-link" href="{% url 'myprofile:experience' %}" id="fontnav">Skills</a>
        </li>
   
       <li class="nav-item">
         <a class="nav-link" href="{% url 'myprofile:skills' %}" id="fontnav">Activities</a>
       </li>
       <li class="nav-item">
         <a class="nav-link" href="{% url 'myprofile:contact' %}" id="fontnav">Contact</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'myprofile:quotes' %}" id="fontnav">Quotes</a>
      </ul>
     </div>
    </div>
   </nav>
       <div id="bg4">
            <div class= "container-fluid-padding">
                <div class="col-xs-12" id="tulisanactivities">
                    Activities
                </div>

                <div class="col-xs-12 col-md-6" id="pengalamankiri">
                    <div id="aktivitas1">Staff of Sponsorship <br> <span style="font-weight: normal;font-style: normal">COMPFEST 11</span> 
                    </div> 
                    <div id="aktivitas2">Member of Entrepreneurship SIG <br> <span style="font-weight: normal;font-style: normal">SISTEM Fasilkom UI</span> 
                    </div>
                    <div id="aktivitas3">Head of Entrepreneurship Division<br><span style="font-weight: normal;font-style: normal">SMAN 78</span> 
                    </div>
                </div>

                <div class="col-xs-12">                  
                    <div id="aktivitas4">LO Artist<br> <span style="font-weight: normal;font-style: normal">Widelanes Festival</span> 
                    </div> 
                    <div id="aktivitas5">Vice Project Officer Senior Prom <br> <span style="font-weight: normal;font-style: normal">SMAN 78</span> 
                    </div>
                    <div id="aktivitas6">Project Officer SMAN 78 Annivesary<br><span style="font-weight: normal;font-style: normal">SMAN 78</span> 
                    </div>                  
                </div>

            </div>
          </div>
        </body>

myprofile/templates/experience.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My Website</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'Profile.css' %}">
    <link rel= "shortcut icon" href="logo.ico" type="image/x-icon">
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-white sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><img id="logo" src="{% static 'Images/Logo.png' %}"></a>

         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
          <span class="navbar-toggler-icon"></span>
         </button>
       
         <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
       
                <li class="nav-item active">
                        <a class="nav-link" href="{% url 'myprofile:profile' %}" id="fontnav">Home</a>
                       </li>
                   
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:experience' %}" id="fontnav">Skills</a>
                        </li>
                   
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:skills' %}" id="fontnav">Activities</a>
                       </li>
                       <li class="nav-item">
                         <a class="nav-link" href="{% url 'myprofile:contact' %}" id="fontnav">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'myprofile:quotes' %}" id="fontnav">Quotes</a>
          </ul>
         </div>
        </div>
       </nav>
    <div id="bg3">
        <img src="{% static 'Images/bhaski1.JPG' %}" alt="bhaski" id ="background3">
        <div class="col-xs-12" id="skillkanan">
            Business Planning <br> Java <br> Microsoft Office<br>
        </div>

        <div class="col-xs-12 col-md-6" id="skillkiri">                  
          Leadership <br> Project Management <br> Python
        </div>

        <div class="col-xs-12" id="skillbawah">
            HTML & CSS
        </div>

      </div>
</body>